//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contratistas()
        {
            this.ContratosCon_Arq = new HashSet<ContratosCon_Arq>();
            this.ContratosCon_Alb = new HashSet<ContratosCon_Alb>();
        }
    
        public int codigoC { get; set; }
        public string nombreCompleto { get; set; }
        public byte[] foto { get; set; }
        public string ciudad { get; set; }
        public string domicilio { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratosCon_Arq> ContratosCon_Arq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratosCon_Alb> ContratosCon_Alb { get; set; }
    }
}
