//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CONSTRUCTIONEntities : DbContext
    {
        public DB_CONSTRUCTIONEntities()
            : base("name=DB_CONSTRUCTIONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Albaniles> Albaniles { get; set; }
        public virtual DbSet<Arquitectos> Arquitectos { get; set; }
        public virtual DbSet<Contratistas> Contratistas { get; set; }
        public virtual DbSet<ContratosCon_Alb> ContratosCon_Alb { get; set; }
        public virtual DbSet<ContratosCon_Arq> ContratosCon_Arq { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
